language: erlang
otp_release:
  - 18.3

sudo: false
install: true
script:
  - ./rebar3 xref
  #- ./rebar3 dialyzer # need to disable this for the damn protobuff

branches:
  only:
  - master
  - dev
  - test
