#!/bin/bash

if [ ! -d "/data/dalmatinerproxy" ]; then
    mkdir -p /data/dalmatinerpx
fi

if [ ! -d "/data/dalmatinerproxy/log" ]; then
    mkdir -p /data/dalmatinerpx/log
fi

# Sort out file permissions
if [[ $(id dalmatinerproxy 2>/dev/null) ]] ;then
    chown -R dalmatinerpx:dalmatinerpx /data/dalmatinerpx
fi

CONFFILE=/data/dalmatinerpx/etc/dpx.conf

if [ ! -f "${CONFFILE}" ]
then
    echo "Creating new configuration from example file."
    cp ${CONFFILE}.example ${CONFFILE}
else
    echo "Please update your configuration according to the update manual!"
fi
